services:
  mysql_db:
    image: mysql:latest
    container_name: rema-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    networks:
      - customnetwork
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ${SQL_SCRIPT}:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "-uroot",
          "-p${DB_PASSWORD}",
          "ping",
          "-h",
          "localhost",
        ]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: ./rema-backend
      dockerfile: Dockerfile
    container_name: rema-backend-container
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes: # uncomment only for real time code changes
      - ./rema-backend:/app/rema-backend
      - /app/rema-backend/node_modules
    user: "node"
    networks:
      - customnetwork
    env_file:
      - .env

  frontend:
    build:
      context: ./rema-frontend
      dockerfile: Dockerfile
    container_name: rema-frontend-container
    depends_on:
      - backend
    ports:
      - 8080:8080 # change the port to 8080:8080 for real time changes and 8080:80 for production
    volumes: # uncomment only for real time code changes
      - ./rema-frontend:/app/rema-frontend
      - /app/rema-frontend/node_modules
    networks:
      - customnetwork

networks:
  customnetwork:

volumes:
  mysql_data:
