services:
  frontend:
    build:
      context: ./rema-frontend
      dockerfile: Dockerfile
    container_name: rema-frontend-container
    depends_on:
      - backend
    ports:
      - 8080:8080
    volumes: #for real time code changes
      - ./rema-frontend:/app/rema-frontend
    networks:
      - customnetwork

  backend:
    build:
      context: ./rema-backend
      dockerfile: Dockerfile
    container_name: rema-backend-container
    ports:
      - 8000:8000
    volumes: #for real time code changes
      - ./rema-backend:/app/rema-backend
    user: "node"
    networks:
      - customnetwork
    env_file:
      - .env

  mysql_db:
    image: mysql:latest
    container_name: rema-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    ports:
      - "3307:3306"
    networks:
      - customnetwork
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./mysql-init-scripts:/docker-entrypoint-initdb.d  # Mount initialization scripts such as creating tables from folder mysql-init-scripts outside of the container

networks:
  customnetwork:

volumes:
  mysql_data:
