services:
  frontend:
    build:
      context: ./rema-frontend
      dockerfile: Dockerfile
    container_name: rema-frontend-container
    depends_on:
      - backend
    ports:
      - 8080:8080 #change to 80 for docker compose
    volumes: #for real time code changes
      - ./rema-frontend:/app/rema-frontend
    user: "node"
    networks:
      - customnetwork

  backend:
    build:
      context: ./rema-backend
      dockerfile: Dockerfile
    container_name: rema-backend-container
    ports:
      - 8000:8000
    volumes: #for real time code changes
      - ./rema-backend:/app/rema-backend
    networks:
      - customnetwork
    env_file:
      - .env

#mysql_db:
#  image: mysql:latest
#  container_name: mysql-container
#  restart: always
#  ports:
#    - "3306:3306"
#  networks:
#    - customnetwork
#  env_file:
#    - .env

networks:
  customnetwork:
